# Generated by Django 4.2.7 on 2023-12-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_blog_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
